// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdubcdedgtesrypicboc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kdWJjZGVkZ3Rlc3J5cGljYm9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDY3NzcsImV4cCI6MjA2NTgyMjc3N30.j7kNTAfr_eeQ70yedzOyrPNSbZFiajdCM-jvYNe_Os0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);